---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation E-Series
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez les systèmes E-Series
      url: "/task-discover-e-series.html"
  - title: Gestion des systèmes E-Series
    entries:
    - title: Affichez vos systèmes E-Series
      url: "/task-view-e-series.html"
    - title: Supprimez un environnement de travail
      url: "/task-remove-e-series.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez les systèmes E-Series
      url: "/task-discover-e-series.html"
  - title: Gestion des systèmes E-Series
    links:
    - title: Affichez vos systèmes E-Series
      url: "/task-view-e-series.html"
    - title: Supprimez un environnement de travail
      url: "/task-remove-e-series.html"
  - title: Liens connexes
    links:
    - title: Documentation E-Series pour la gestion en dehors de BlueXP
      url: https://docs.netapp.com/us-en/e-series-family/
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
